"""Added some fields in UserPassword

Revision ID: 149a08adfae9
Revises: 387500507c8c
Create Date: 2025-12-13 12:26:56.297873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '149a08adfae9'
down_revision: Union[str, Sequence[str], None] = '387500507c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userpasswords', 'application_icon',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userpasswords', 'application_icon',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
