"""Added some fields in UserPassword

Revision ID: 387500507c8c
Revises: ee274d7259b5
Create Date: 2025-12-13 09:29:53.360446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '387500507c8c'
down_revision: Union[str, Sequence[str], None] = 'ee274d7259b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userpasswords', sa.Column('user_gmail', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('userpasswords', sa.Column('user_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('userpasswords', sa.Column('application', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('userpasswords', sa.Column('application_icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userpasswords', 'application_icon')
    op.drop_column('userpasswords', 'application')
    op.drop_column('userpasswords', 'user_password')
    op.drop_column('userpasswords', 'user_gmail')
    # ### end Alembic commands ###
