"""Add User and UserPasswords tables

Revision ID: ee274d7259b5
Revises: 5c8061cb81c3
Create Date: 2025-12-13 09:23:29.549835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee274d7259b5'
down_revision: Union[str, Sequence[str], None] = '5c8061cb81c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userpasswords', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'userpasswords', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userpasswords', type_='foreignkey')
    op.drop_column('userpasswords', 'user_id')
    # ### end Alembic commands ###
